baseURL = "http://ammaturo.de/"
languageCode = "de-DE"
title = "Anna Ammaturo"
theme = "hugo-creative-portfolio-theme"
relativeURLs = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"

[[params.navlinks]]
  name = "Home"
  url = "posts/"
  home = true
